### PR TITLE
Update dependencies to resolve braces security

### PR DESCRIPTION
**Pull request by thehig**
https://npmjs.com/advisories/786

### CODE REVIEW

**Comment by rickhanlonii** [comment]
Thanks!

**Comment by thehig** [comment]
@rickhanlonii Will you be updating this in the npm registry?

**Comment by rickhanlonii** [comment]
Done https://www.npmjs.com/package/jest-skipped-reporter/v/0.0.5 👍

**Comment by thehig** [comment]
npm audit warning has disappeared. Legend

**Pull request merged**
